### ISSUE TITLE
[mining] generate works on regtest but not testnet

### ISSUE THREAD

**Issue by ch4ot1c** [BTCPrivate/BTCP-Rebase#102]
`regtest` works fairly well, even with peers.

**Comment by ch4ot1c** [comment]
The problem is just an out-of-memory error on small machines.

Getting `testnet` generate working in a general case isn't a priority until a built-in cpu miner is added.

**Comment by mattpass** [comment]
Was able to absolutely confirm this with richardvt today who bumped up the CPU and it mined 1 block after a few minutes. In a subsequent test of generating 5 blocks it errored out with a timeout, but given enough time it would do it.

It just needs more power and the smaller machines just weren't powerful enough to do a whole block themselves in a reasonable timeframe. Given a lot of time they would of. Therefore generate does work in testnet.

**Comment by interbiznw** [comment]
It has worked the whole time..just not consistently every single time. I have had it fail on a machine then next try on same machine had it work.

Has to have worked or the test net wouldn't have had a block to start from

**Comment by dskjkljdas** [comment]
Single block mined AOK, but 5 block generate timed out in CLI but bitcoind was happily sitting there mining in the background even though the CLI reported a timeout indicating it was still mining after the timeout (bitcoind was till live and functioning too)
