### ISSUE TITLE
Reclaim burnt coins for long inactive users

### ISSUE THREAD

**Issue by madtomic** [BTCPrivate/BTCP-Rebase#111]
Reclaim burnt coins for long inactive users, This is for users who had claimed with BTCP client and never moved their coins since the forked as they don't see a reason why. It is is only right thing to do, after all, it's their rightful coins.

Even with ZenCash changing to Horizen and forking few times since forked. My coins are still in the same address as it was forked from Zclassic. I have no reason to move then as I don't need to use them. You guys should think and look into adding a way for owners of un-shielded address to reclaim their burnt coins due to this latest change.

Thanks for reading.

**Comment by interbiznw** [comment]
If you "claimed" with btcp client properly,  nothing would be burnt

**Comment by mattpass** [comment]
Agreed, this unfortunately is down to not claiming properly. It has nothing to do with rebase codebase so closing. If you want to discuss your idea re claiming your burnt coins, you can do so on the social media channels, this repo is not the place to raise this idea.

**Comment by madtomic** [comment]
Thank you for your time. I will look into class action lawsuit.
