### ISSUE TITLE
~/.btcp?

### ISSUE THREAD

**Issue by ch4ot1c** [BTCPrivate/BTCP-Rebase#20]
I see that, when running `bitcoind`, the created datadir is at `~/.btcp`. Previously, it was `~/.btcprivate`. Is this change intentional and safe in all cases?

**Comment by interbiznw** [comment]
IMO it is safe and used as to not overwrite the datadir if running the node on a node along a current bitcoin private node, or bitcoin node.

**Comment by ch4ot1c** [comment]
Alright - we'll keep the directory as `~/.btcp` for the duration of development. I've created https://github.com/BTCPrivate/BTCP-Rebase/issues/29 for related issues.
