### ISSUE TITLE
boost::array -> std::array

### ISSUE THREAD

**Issue by ch4ot1c** [BTCPrivate/BTCP-Rebase#5]
https://github.com/zcash/zcash/pull/3237/commits/a6bbb26e08a51d92b4f64ef984b95e3078fdde9c

Do the same.

**Comment by TheComputerScienceEducator** [comment]
What does this change do? Willing to put in the time to make the changes, but am unsure of the purpose.

**Comment by ch4ot1c** [comment]
`boost::array` has been replaced with `std::array` in the main codebase; C++11 will require us to keep boost around though (until C++14), for `apply_visitor` and similar. This is a longer running task; renaming and closing for now.
