### ISSUE TITLE
Replace Bitcoin Core URLs and Copy with Bitcoin Private relevant text

### ISSUE THREAD

**Issue by TheComputerScienceEducator** [BTCPrivate/BTCP-Rebase#6]
The presented link when creating a new issue takes you to bitcoin core github.

**Comment by ch4ot1c** [comment]
https://github.com/BTCPrivate/BTCP-Rebase/pull/8

This can be closed once https://github.com/BTCPrivate/BTCP-Rebase/issues/20 is decided.

**Comment by ch4ot1c** [comment]
Open a new issue/PR for further doc changes.
